/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authOtpImport } from './routes/(auth)/otp'
import { Route as auth500Import } from './routes/(auth)/500'

// Create Virtual Routes

const errors503LazyImport = createFileRoute('/(errors)/503')()
const errors500LazyImport = createFileRoute('/(errors)/500')()
const errors404LazyImport = createFileRoute('/(errors)/404')()
const errors403LazyImport = createFileRoute('/(errors)/403')()
const errors401LazyImport = createFileRoute('/(errors)/401')()
const authSignUpLazyImport = createFileRoute('/(auth)/sign-up')()
const authSignIn2LazyImport = createFileRoute('/(auth)/sign-in-2')()
const authForgotPasswordLazyImport = createFileRoute(
  '/(auth)/forgot-password',
)()
const AuthenticatedSettingsRouteLazyImport = createFileRoute(
  '/_authenticated/settings',
)()
const AuthenticatedUsersIndexLazyImport = createFileRoute(
  '/_authenticated/users/',
)()
const AuthenticatedSetupIndexLazyImport = createFileRoute(
  '/_authenticated/setup/',
)()
const AuthenticatedSettingsIndexLazyImport = createFileRoute(
  '/_authenticated/settings/',
)()
const AuthenticatedRadiologyIndexLazyImport = createFileRoute(
  '/_authenticated/radiology/',
)()
const AuthenticatedPatientsRegistrationIndexLazyImport = createFileRoute(
  '/_authenticated/patients-registration/',
)()
const AuthenticatedOperationTheaterIndexLazyImport = createFileRoute(
  '/_authenticated/operation-theater/',
)()
const AuthenticatedLaporatoryIndexLazyImport = createFileRoute(
  '/_authenticated/laporatory/',
)()
const AuthenticatedInventoryIndexLazyImport = createFileRoute(
  '/_authenticated/inventory/',
)()
const AuthenticatedInPatientManagementIndexLazyImport = createFileRoute(
  '/_authenticated/in-patient-management/',
)()
const AuthenticatedHelpCenterIndexLazyImport = createFileRoute(
  '/_authenticated/help-center/',
)()
const AuthenticatedEmergencyIndexLazyImport = createFileRoute(
  '/_authenticated/emergency/',
)()
const AuthenticatedClinicalManagementIndexLazyImport = createFileRoute(
  '/_authenticated/clinical-management/',
)()
const AuthenticatedBloodBankIndexLazyImport = createFileRoute(
  '/_authenticated/blood-bank/',
)()
const AuthenticatedAppointmentsIndexLazyImport = createFileRoute(
  '/_authenticated/appointments/',
)()
const AuthenticatedSetupLaporatoryLazyImport = createFileRoute(
  '/_authenticated/setup/laporatory',
)()
const AuthenticatedSetupInventoryLazyImport = createFileRoute(
  '/_authenticated/setup/inventory',
)()
const AuthenticatedSetupCustomTemplateLazyImport = createFileRoute(
  '/_authenticated/setup/custom-template',
)()
const AuthenticatedSettingsNotificationsLazyImport = createFileRoute(
  '/_authenticated/settings/notifications',
)()
const AuthenticatedSettingsDisplayLazyImport = createFileRoute(
  '/_authenticated/settings/display',
)()
const AuthenticatedSettingsAppearanceLazyImport = createFileRoute(
  '/_authenticated/settings/appearance',
)()
const AuthenticatedSettingsAccountLazyImport = createFileRoute(
  '/_authenticated/settings/account',
)()
const AuthenticatedMaintenanceSoftwareReportsLazyImport = createFileRoute(
  '/_authenticated/maintenance/software-reports',
)()

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const errors503LazyRoute = errors503LazyImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))

const errors500LazyRoute = errors500LazyImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))

const errors404LazyRoute = errors404LazyImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))

const errors403LazyRoute = errors403LazyImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))

const errors401LazyRoute = errors401LazyImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))

const authSignUpLazyRoute = authSignUpLazyImport
  .update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up.lazy').then((d) => d.Route))

const authSignIn2LazyRoute = authSignIn2LazyImport
  .update({
    id: '/(auth)/sign-in-2',
    path: '/sign-in-2',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-in-2.lazy').then((d) => d.Route))

const authForgotPasswordLazyRoute = authForgotPasswordLazyImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsRouteLazyRoute =
  AuthenticatedSettingsRouteLazyImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/route.lazy').then((d) => d.Route),
  )

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const authOtpRoute = authOtpImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRoute,
} as any)

const auth500Route = auth500Import.update({
  id: '/(auth)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedUsersIndexLazyRoute =
  AuthenticatedUsersIndexLazyImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/users/index.lazy').then((d) => d.Route),
  )

const AuthenticatedSetupIndexLazyRoute =
  AuthenticatedSetupIndexLazyImport.update({
    id: '/setup/',
    path: '/setup/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/setup/index.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsIndexLazyRoute =
  AuthenticatedSettingsIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/index.lazy').then((d) => d.Route),
  )

const AuthenticatedRadiologyIndexLazyRoute =
  AuthenticatedRadiologyIndexLazyImport.update({
    id: '/radiology/',
    path: '/radiology/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/radiology/index.lazy').then((d) => d.Route),
  )

const AuthenticatedPatientsRegistrationIndexLazyRoute =
  AuthenticatedPatientsRegistrationIndexLazyImport.update({
    id: '/patients-registration/',
    path: '/patients-registration/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/patients-registration/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedOperationTheaterIndexLazyRoute =
  AuthenticatedOperationTheaterIndexLazyImport.update({
    id: '/operation-theater/',
    path: '/operation-theater/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/operation-theater/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedLaporatoryIndexLazyRoute =
  AuthenticatedLaporatoryIndexLazyImport.update({
    id: '/laporatory/',
    path: '/laporatory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/laporatory/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedInventoryIndexLazyRoute =
  AuthenticatedInventoryIndexLazyImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/inventory/index.lazy').then((d) => d.Route),
  )

const AuthenticatedInPatientManagementIndexLazyRoute =
  AuthenticatedInPatientManagementIndexLazyImport.update({
    id: '/in-patient-management/',
    path: '/in-patient-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/in-patient-management/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedHelpCenterIndexLazyRoute =
  AuthenticatedHelpCenterIndexLazyImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/help-center/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedEmergencyIndexLazyRoute =
  AuthenticatedEmergencyIndexLazyImport.update({
    id: '/emergency/',
    path: '/emergency/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/emergency/index.lazy').then((d) => d.Route),
  )

const AuthenticatedClinicalManagementIndexLazyRoute =
  AuthenticatedClinicalManagementIndexLazyImport.update({
    id: '/clinical-management/',
    path: '/clinical-management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/clinical-management/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedBloodBankIndexLazyRoute =
  AuthenticatedBloodBankIndexLazyImport.update({
    id: '/blood-bank/',
    path: '/blood-bank/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/blood-bank/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedAppointmentsIndexLazyRoute =
  AuthenticatedAppointmentsIndexLazyImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/appointments/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSetupLaporatoryLazyRoute =
  AuthenticatedSetupLaporatoryLazyImport.update({
    id: '/setup/laporatory',
    path: '/setup/laporatory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/setup/laporatory.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSetupInventoryLazyRoute =
  AuthenticatedSetupInventoryLazyImport.update({
    id: '/setup/inventory',
    path: '/setup/inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/setup/inventory.lazy').then((d) => d.Route),
  )

const AuthenticatedSetupCustomTemplateLazyRoute =
  AuthenticatedSetupCustomTemplateLazyImport.update({
    id: '/setup/custom-template',
    path: '/setup/custom-template',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/setup/custom-template.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsNotificationsLazyRoute =
  AuthenticatedSettingsNotificationsLazyImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/notifications.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsDisplayLazyRoute =
  AuthenticatedSettingsDisplayLazyImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/display.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsAppearanceLazyRoute =
  AuthenticatedSettingsAppearanceLazyImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/appearance.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsAccountLazyRoute =
  AuthenticatedSettingsAccountLazyImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/account.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedMaintenanceSoftwareReportsLazyRoute =
  AuthenticatedMaintenanceSoftwareReportsLazyImport.update({
    id: '/maintenance/software-reports',
    path: '/maintenance/software-reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/maintenance/software-reports.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/500': {
      id: '/(auth)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof auth500Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2LazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpLazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/maintenance/software-reports': {
      id: '/_authenticated/maintenance/software-reports'
      path: '/maintenance/software-reports'
      fullPath: '/maintenance/software-reports'
      preLoaderRoute: typeof AuthenticatedMaintenanceSoftwareReportsLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/setup/custom-template': {
      id: '/_authenticated/setup/custom-template'
      path: '/setup/custom-template'
      fullPath: '/setup/custom-template'
      preLoaderRoute: typeof AuthenticatedSetupCustomTemplateLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/setup/inventory': {
      id: '/_authenticated/setup/inventory'
      path: '/setup/inventory'
      fullPath: '/setup/inventory'
      preLoaderRoute: typeof AuthenticatedSetupInventoryLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/setup/laporatory': {
      id: '/_authenticated/setup/laporatory'
      path: '/setup/laporatory'
      fullPath: '/setup/laporatory'
      preLoaderRoute: typeof AuthenticatedSetupLaporatoryLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/appointments/': {
      id: '/_authenticated/appointments/'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/blood-bank/': {
      id: '/_authenticated/blood-bank/'
      path: '/blood-bank'
      fullPath: '/blood-bank'
      preLoaderRoute: typeof AuthenticatedBloodBankIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/clinical-management/': {
      id: '/_authenticated/clinical-management/'
      path: '/clinical-management'
      fullPath: '/clinical-management'
      preLoaderRoute: typeof AuthenticatedClinicalManagementIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/emergency/': {
      id: '/_authenticated/emergency/'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AuthenticatedEmergencyIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/in-patient-management/': {
      id: '/_authenticated/in-patient-management/'
      path: '/in-patient-management'
      fullPath: '/in-patient-management'
      preLoaderRoute: typeof AuthenticatedInPatientManagementIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/laporatory/': {
      id: '/_authenticated/laporatory/'
      path: '/laporatory'
      fullPath: '/laporatory'
      preLoaderRoute: typeof AuthenticatedLaporatoryIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/operation-theater/': {
      id: '/_authenticated/operation-theater/'
      path: '/operation-theater'
      fullPath: '/operation-theater'
      preLoaderRoute: typeof AuthenticatedOperationTheaterIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/patients-registration/': {
      id: '/_authenticated/patients-registration/'
      path: '/patients-registration'
      fullPath: '/patients-registration'
      preLoaderRoute: typeof AuthenticatedPatientsRegistrationIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/radiology/': {
      id: '/_authenticated/radiology/'
      path: '/radiology'
      fullPath: '/radiology'
      preLoaderRoute: typeof AuthenticatedRadiologyIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/setup/': {
      id: '/_authenticated/setup/'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedSettingsRouteLazyRouteChildren {
  AuthenticatedSettingsAccountLazyRoute: typeof AuthenticatedSettingsAccountLazyRoute
  AuthenticatedSettingsAppearanceLazyRoute: typeof AuthenticatedSettingsAppearanceLazyRoute
  AuthenticatedSettingsDisplayLazyRoute: typeof AuthenticatedSettingsDisplayLazyRoute
  AuthenticatedSettingsNotificationsLazyRoute: typeof AuthenticatedSettingsNotificationsLazyRoute
  AuthenticatedSettingsIndexLazyRoute: typeof AuthenticatedSettingsIndexLazyRoute
}

const AuthenticatedSettingsRouteLazyRouteChildren: AuthenticatedSettingsRouteLazyRouteChildren =
  {
    AuthenticatedSettingsAccountLazyRoute:
      AuthenticatedSettingsAccountLazyRoute,
    AuthenticatedSettingsAppearanceLazyRoute:
      AuthenticatedSettingsAppearanceLazyRoute,
    AuthenticatedSettingsDisplayLazyRoute:
      AuthenticatedSettingsDisplayLazyRoute,
    AuthenticatedSettingsNotificationsLazyRoute:
      AuthenticatedSettingsNotificationsLazyRoute,
    AuthenticatedSettingsIndexLazyRoute: AuthenticatedSettingsIndexLazyRoute,
  }

const AuthenticatedSettingsRouteLazyRouteWithChildren =
  AuthenticatedSettingsRouteLazyRoute._addFileChildren(
    AuthenticatedSettingsRouteLazyRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteLazyRoute: typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMaintenanceSoftwareReportsLazyRoute: typeof AuthenticatedMaintenanceSoftwareReportsLazyRoute
  AuthenticatedSetupCustomTemplateLazyRoute: typeof AuthenticatedSetupCustomTemplateLazyRoute
  AuthenticatedSetupInventoryLazyRoute: typeof AuthenticatedSetupInventoryLazyRoute
  AuthenticatedSetupLaporatoryLazyRoute: typeof AuthenticatedSetupLaporatoryLazyRoute
  AuthenticatedAppointmentsIndexLazyRoute: typeof AuthenticatedAppointmentsIndexLazyRoute
  AuthenticatedBloodBankIndexLazyRoute: typeof AuthenticatedBloodBankIndexLazyRoute
  AuthenticatedClinicalManagementIndexLazyRoute: typeof AuthenticatedClinicalManagementIndexLazyRoute
  AuthenticatedEmergencyIndexLazyRoute: typeof AuthenticatedEmergencyIndexLazyRoute
  AuthenticatedHelpCenterIndexLazyRoute: typeof AuthenticatedHelpCenterIndexLazyRoute
  AuthenticatedInPatientManagementIndexLazyRoute: typeof AuthenticatedInPatientManagementIndexLazyRoute
  AuthenticatedInventoryIndexLazyRoute: typeof AuthenticatedInventoryIndexLazyRoute
  AuthenticatedLaporatoryIndexLazyRoute: typeof AuthenticatedLaporatoryIndexLazyRoute
  AuthenticatedOperationTheaterIndexLazyRoute: typeof AuthenticatedOperationTheaterIndexLazyRoute
  AuthenticatedPatientsRegistrationIndexLazyRoute: typeof AuthenticatedPatientsRegistrationIndexLazyRoute
  AuthenticatedRadiologyIndexLazyRoute: typeof AuthenticatedRadiologyIndexLazyRoute
  AuthenticatedSetupIndexLazyRoute: typeof AuthenticatedSetupIndexLazyRoute
  AuthenticatedUsersIndexLazyRoute: typeof AuthenticatedUsersIndexLazyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteLazyRoute:
    AuthenticatedSettingsRouteLazyRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMaintenanceSoftwareReportsLazyRoute:
    AuthenticatedMaintenanceSoftwareReportsLazyRoute,
  AuthenticatedSetupCustomTemplateLazyRoute:
    AuthenticatedSetupCustomTemplateLazyRoute,
  AuthenticatedSetupInventoryLazyRoute: AuthenticatedSetupInventoryLazyRoute,
  AuthenticatedSetupLaporatoryLazyRoute: AuthenticatedSetupLaporatoryLazyRoute,
  AuthenticatedAppointmentsIndexLazyRoute:
    AuthenticatedAppointmentsIndexLazyRoute,
  AuthenticatedBloodBankIndexLazyRoute: AuthenticatedBloodBankIndexLazyRoute,
  AuthenticatedClinicalManagementIndexLazyRoute:
    AuthenticatedClinicalManagementIndexLazyRoute,
  AuthenticatedEmergencyIndexLazyRoute: AuthenticatedEmergencyIndexLazyRoute,
  AuthenticatedHelpCenterIndexLazyRoute: AuthenticatedHelpCenterIndexLazyRoute,
  AuthenticatedInPatientManagementIndexLazyRoute:
    AuthenticatedInPatientManagementIndexLazyRoute,
  AuthenticatedInventoryIndexLazyRoute: AuthenticatedInventoryIndexLazyRoute,
  AuthenticatedLaporatoryIndexLazyRoute: AuthenticatedLaporatoryIndexLazyRoute,
  AuthenticatedOperationTheaterIndexLazyRoute:
    AuthenticatedOperationTheaterIndexLazyRoute,
  AuthenticatedPatientsRegistrationIndexLazyRoute:
    AuthenticatedPatientsRegistrationIndexLazyRoute,
  AuthenticatedRadiologyIndexLazyRoute: AuthenticatedRadiologyIndexLazyRoute,
  AuthenticatedSetupIndexLazyRoute: AuthenticatedSetupIndexLazyRoute,
  AuthenticatedUsersIndexLazyRoute: AuthenticatedUsersIndexLazyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/500': typeof errors500LazyRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/maintenance/software-reports': typeof AuthenticatedMaintenanceSoftwareReportsLazyRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/setup/custom-template': typeof AuthenticatedSetupCustomTemplateLazyRoute
  '/setup/inventory': typeof AuthenticatedSetupInventoryLazyRoute
  '/setup/laporatory': typeof AuthenticatedSetupLaporatoryLazyRoute
  '/appointments': typeof AuthenticatedAppointmentsIndexLazyRoute
  '/blood-bank': typeof AuthenticatedBloodBankIndexLazyRoute
  '/clinical-management': typeof AuthenticatedClinicalManagementIndexLazyRoute
  '/emergency': typeof AuthenticatedEmergencyIndexLazyRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/in-patient-management': typeof AuthenticatedInPatientManagementIndexLazyRoute
  '/inventory': typeof AuthenticatedInventoryIndexLazyRoute
  '/laporatory': typeof AuthenticatedLaporatoryIndexLazyRoute
  '/operation-theater': typeof AuthenticatedOperationTheaterIndexLazyRoute
  '/patients-registration': typeof AuthenticatedPatientsRegistrationIndexLazyRoute
  '/radiology': typeof AuthenticatedRadiologyIndexLazyRoute
  '/settings/': typeof AuthenticatedSettingsIndexLazyRoute
  '/setup': typeof AuthenticatedSetupIndexLazyRoute
  '/users': typeof AuthenticatedUsersIndexLazyRoute
}

export interface FileRoutesByTo {
  '/500': typeof errors500LazyRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/maintenance/software-reports': typeof AuthenticatedMaintenanceSoftwareReportsLazyRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/setup/custom-template': typeof AuthenticatedSetupCustomTemplateLazyRoute
  '/setup/inventory': typeof AuthenticatedSetupInventoryLazyRoute
  '/setup/laporatory': typeof AuthenticatedSetupLaporatoryLazyRoute
  '/appointments': typeof AuthenticatedAppointmentsIndexLazyRoute
  '/blood-bank': typeof AuthenticatedBloodBankIndexLazyRoute
  '/clinical-management': typeof AuthenticatedClinicalManagementIndexLazyRoute
  '/emergency': typeof AuthenticatedEmergencyIndexLazyRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/in-patient-management': typeof AuthenticatedInPatientManagementIndexLazyRoute
  '/inventory': typeof AuthenticatedInventoryIndexLazyRoute
  '/laporatory': typeof AuthenticatedLaporatoryIndexLazyRoute
  '/operation-theater': typeof AuthenticatedOperationTheaterIndexLazyRoute
  '/patients-registration': typeof AuthenticatedPatientsRegistrationIndexLazyRoute
  '/radiology': typeof AuthenticatedRadiologyIndexLazyRoute
  '/settings': typeof AuthenticatedSettingsIndexLazyRoute
  '/setup': typeof AuthenticatedSetupIndexLazyRoute
  '/users': typeof AuthenticatedUsersIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/500': typeof auth500Route
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/sign-in-2': typeof authSignIn2LazyRoute
  '/(auth)/sign-up': typeof authSignUpLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/maintenance/software-reports': typeof AuthenticatedMaintenanceSoftwareReportsLazyRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/_authenticated/setup/custom-template': typeof AuthenticatedSetupCustomTemplateLazyRoute
  '/_authenticated/setup/inventory': typeof AuthenticatedSetupInventoryLazyRoute
  '/_authenticated/setup/laporatory': typeof AuthenticatedSetupLaporatoryLazyRoute
  '/_authenticated/appointments/': typeof AuthenticatedAppointmentsIndexLazyRoute
  '/_authenticated/blood-bank/': typeof AuthenticatedBloodBankIndexLazyRoute
  '/_authenticated/clinical-management/': typeof AuthenticatedClinicalManagementIndexLazyRoute
  '/_authenticated/emergency/': typeof AuthenticatedEmergencyIndexLazyRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/_authenticated/in-patient-management/': typeof AuthenticatedInPatientManagementIndexLazyRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexLazyRoute
  '/_authenticated/laporatory/': typeof AuthenticatedLaporatoryIndexLazyRoute
  '/_authenticated/operation-theater/': typeof AuthenticatedOperationTheaterIndexLazyRoute
  '/_authenticated/patients-registration/': typeof AuthenticatedPatientsRegistrationIndexLazyRoute
  '/_authenticated/radiology/': typeof AuthenticatedRadiologyIndexLazyRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexLazyRoute
  '/_authenticated/setup/': typeof AuthenticatedSetupIndexLazyRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/500'
    | '/otp'
    | '/sign-in'
    | '/settings'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/'
    | '/maintenance/software-reports'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/setup/custom-template'
    | '/setup/inventory'
    | '/setup/laporatory'
    | '/appointments'
    | '/blood-bank'
    | '/clinical-management'
    | '/emergency'
    | '/help-center'
    | '/in-patient-management'
    | '/inventory'
    | '/laporatory'
    | '/operation-theater'
    | '/patients-registration'
    | '/radiology'
    | '/settings/'
    | '/setup'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/500'
    | '/otp'
    | '/sign-in'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/'
    | '/maintenance/software-reports'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/setup/custom-template'
    | '/setup/inventory'
    | '/setup/laporatory'
    | '/appointments'
    | '/blood-bank'
    | '/clinical-management'
    | '/emergency'
    | '/help-center'
    | '/in-patient-management'
    | '/inventory'
    | '/laporatory'
    | '/operation-theater'
    | '/patients-registration'
    | '/radiology'
    | '/settings'
    | '/setup'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/500'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/maintenance/software-reports'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/setup/custom-template'
    | '/_authenticated/setup/inventory'
    | '/_authenticated/setup/laporatory'
    | '/_authenticated/appointments/'
    | '/_authenticated/blood-bank/'
    | '/_authenticated/clinical-management/'
    | '/_authenticated/emergency/'
    | '/_authenticated/help-center/'
    | '/_authenticated/in-patient-management/'
    | '/_authenticated/inventory/'
    | '/_authenticated/laporatory/'
    | '/_authenticated/operation-theater/'
    | '/_authenticated/patients-registration/'
    | '/_authenticated/radiology/'
    | '/_authenticated/settings/'
    | '/_authenticated/setup/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  auth500Route: typeof auth500Route
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authSignIn2LazyRoute: typeof authSignIn2LazyRoute
  authSignUpLazyRoute: typeof authSignUpLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  auth500Route: auth500Route,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authSignIn2LazyRoute: authSignIn2LazyRoute,
  authSignUpLazyRoute: authSignUpLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/(auth)/500",
        "/(auth)/otp",
        "/(auth)/sign-in",
        "/(auth)/forgot-password",
        "/(auth)/sign-in-2",
        "/(auth)/sign-up",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/settings",
        "/_authenticated/",
        "/_authenticated/maintenance/software-reports",
        "/_authenticated/setup/custom-template",
        "/_authenticated/setup/inventory",
        "/_authenticated/setup/laporatory",
        "/_authenticated/appointments/",
        "/_authenticated/blood-bank/",
        "/_authenticated/clinical-management/",
        "/_authenticated/emergency/",
        "/_authenticated/help-center/",
        "/_authenticated/in-patient-management/",
        "/_authenticated/inventory/",
        "/_authenticated/laporatory/",
        "/_authenticated/operation-theater/",
        "/_authenticated/patients-registration/",
        "/_authenticated/radiology/",
        "/_authenticated/setup/",
        "/_authenticated/users/"
      ]
    },
    "/(auth)/500": {
      "filePath": "(auth)/500.tsx"
    },
    "/(auth)/otp": {
      "filePath": "(auth)/otp.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/account",
        "/_authenticated/settings/appearance",
        "/_authenticated/settings/display",
        "/_authenticated/settings/notifications",
        "/_authenticated/settings/"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.lazy.tsx"
    },
    "/(auth)/sign-in-2": {
      "filePath": "(auth)/sign-in-2.lazy.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.lazy.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.lazy.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.lazy.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.lazy.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.lazy.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.lazy.tsx"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/maintenance/software-reports": {
      "filePath": "_authenticated/maintenance/software-reports.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/account": {
      "filePath": "_authenticated/settings/account.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/appearance": {
      "filePath": "_authenticated/settings/appearance.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/display": {
      "filePath": "_authenticated/settings/display.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/notifications": {
      "filePath": "_authenticated/settings/notifications.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/setup/custom-template": {
      "filePath": "_authenticated/setup/custom-template.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/setup/inventory": {
      "filePath": "_authenticated/setup/inventory.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/setup/laporatory": {
      "filePath": "_authenticated/setup/laporatory.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/appointments/": {
      "filePath": "_authenticated/appointments/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/blood-bank/": {
      "filePath": "_authenticated/blood-bank/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/clinical-management/": {
      "filePath": "_authenticated/clinical-management/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/emergency/": {
      "filePath": "_authenticated/emergency/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/help-center/": {
      "filePath": "_authenticated/help-center/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/in-patient-management/": {
      "filePath": "_authenticated/in-patient-management/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/inventory/": {
      "filePath": "_authenticated/inventory/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/laporatory/": {
      "filePath": "_authenticated/laporatory/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/operation-theater/": {
      "filePath": "_authenticated/operation-theater/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/patients-registration/": {
      "filePath": "_authenticated/patients-registration/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/radiology/": {
      "filePath": "_authenticated/radiology/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/setup/": {
      "filePath": "_authenticated/setup/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/users/": {
      "filePath": "_authenticated/users/index.lazy.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
